---
title: "Homework 4"
author: "Samantha Rabinowitz, sar4357"
date: "5/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preliminaries

Included in the R Markdown file but hidden from view to limit the length of this document is the loading of the following packages necessary to use the functions utilized in this assignment: *tidyverse*, *patchwork*, *scales*, *collapse*, *BBmisc*, *devtools*, and *tidycovid19*. Additionally, the code used to write the **cv_summary** function and organization of the data file included in the *tidycovid19* package are also not included in this final knit document.

```{R, include=FALSE}
library(tidyverse)
library(patchwork) # for plotting
library(scales) # for log y axis scale
library(collapse) # for `fmode()` to find mode
library(BBmisc) # for %nin%
library(devtools)
library(tidycovid19)

merged <- download_merged_data(cached = TRUE)
merged <- merged %>%
  group_by(country, iso3c) %>%
  arrange(country, iso3c, date) %>%
  ## new code to replace NAs with zeros
  mutate(
    confirmed = ifelse(is.na(confirmed), 0, confirmed),
    deaths = ifelse(is.na(deaths), 0, deaths),
    recovered = ifelse(is.na(recovered), 0, recovered)
  ) %>%
  ## end of new code
  mutate(
    daily_confirmed = confirmed - lag(confirmed, n = 1),
    daily_deaths = deaths - lag(deaths, n = 1),
    daily_recovered = recovered - lag(recovered, n = 1)
  ) %>%
  mutate(
    daily_confirmed = replace_na(daily_confirmed, 0),
    daily_deaths = replace_na(daily_deaths, 0),
    daily_recovered = replace_na(daily_recovered, 0)
  ) %>%
  ungroup() %>%
  arrange(country, iso3c, date)

add_world1 <- merged %>%
  group_by(date) %>%
  arrange(date) %>%
  summarize(
    country = "World", iso3c = NA,
    confirmed = sum(confirmed, na.rm = TRUE),
    deaths = sum(deaths, na.rm = TRUE),
    recovered = sum(recovered, na.rm = TRUE),
    timestamp = fmode(timestamp)
  ) %>%
  mutate(
    daily_confirmed = confirmed - lag(confirmed, n = 1),
    daily_deaths = deaths - lag(deaths, n = 1),
    daily_recovered = recovered - lag(recovered, n = 1)
  ) %>%
  mutate(
    daily_confirmed = replace_na(daily_confirmed, 0),
    daily_deaths = replace_na(daily_deaths, 0),
    daily_recovered = replace_na(daily_recovered, 0)
  ) %>%
  ungroup() %>%
  arrange(country, iso3c, date)

add_world2 <- merged %>%
  group_by(country, iso3c) %>%
  summarize(
    population = fmode(population),
    land_area_skm = fmode(land_area_skm),
    timestamp = fmode(timestamp)
  ) %>%
  ungroup() %>%
  summarize(
    country = "World", iso3c = NA,
    population = sum(population, na.rm = TRUE),
    land_area_skm = sum(land_area_skm, na.rm = TRUE)
  ) %>%
  mutate(pop_density = population / land_area_skm)

add_world <- left_join(add_world1, add_world2, by = c("country", "iso3c"))
merged <- bind_rows(merged, add_world)

cv_data <- pivot_longer(merged,
  cols = c(
    "confirmed", "deaths", "recovered",
    "daily_confirmed", "daily_deaths", "daily_recovered"
  ),
  names_to = "variable", values_to = "cases"
) %>%
  arrange(country, variable, date) %>%
  rename(area = land_area_skm, density = pop_density) %>%
  mutate(rate = cases / population * 10^6) %>%
  ## new code to omit data before 2020-05-11
  filter(date < "2020-05-11")
## end of new code

cv_summary <- function(d, country_list = "World",
                       plot = TRUE, facet = "country",
                       status = c("confirmed", "deaths", "recovered")) {

  # based on `wes_palettes()` GrandBudapest1, IsleofDogs1, IsleofDogs2
  # from the {wesanderson} package
  my_palette <- c(
    "#5B1A18", "#FD6467", "#F1BB7B", "#D67236",
    "#0F0D0E", "#9986A5", "#79402E", "#CCBA72", "#D9D0D3", "#8D8680",
    "#EAD3BF", "#AA9486", "#B6854D", "#39312F", "#1C1718"
  )

  if (facet == "country") {
    fill <- "variable"
    n <- length(unique(d$variable)) / 2
    # need only half of unique # of variable (3)
  }

  if (facet == "variable") {
    fill <- "country"
    n <- length(country_list)
    # need number of countries
  }

  if ("All" %in% country_list) {
    country_list <- unique(d$country)
    country_list <- setdiff(country_list, "World")
  }

  if ("World" %in% country_list) {
    d <- d %>% filter(country %in% country_list)

    totals <- d %>%
      group_by(variable) %>%
      summarize(
        country = "World",
        cases = max(cases),
        population = max(population),
        area = max(area),
        density = max(density),
        rate = max(rate, na.rm = TRUE),
        on = max(date)
      ) %>%
      select(country, variable, cases, population, area, density, rate, on) %>%
      arrange(variable) %>%
      ungroup()
  }

  if ("World" %nin% country_list) {
    d <- d %>% filter(country %in% country_list)
    totals <- d %>%
      group_by(country, variable) %>%
      summarize(
        cases = max(cases),
        population = max(population),
        area = max(area),
        density = max(density),
        rate = max(rate, na.rm = TRUE),
        on = max(date),
        gdp_capita = fmode(gdp_capita),
        income = fmode(income),
        life_expectancy = fmode(life_expectancy),
        max_sd = max(soc_dist),
        max_mr = max(mov_rest)
      ) %>%
      select(
        country, variable, cases, population, area, density, rate,
        gdp_capita, income, life_expectancy, max_sd, max_mr, on
      ) %>%
      arrange(country, variable) %>%
      ungroup()
  }

  if (plot == TRUE) {
    cc <- filter(d, variable %in% status)
    cum_cases_plot <- ggplot(
      data = cc,
      # use the tidy evaluation pronoun .data to slice the chosen fill
      # variable from the data frame
      aes(
        x = date, y = cases + 1, color = .data[[fill]],
        fill = .data[[fill]]
      )
    ) +
      geom_point(size = 0.5) +
      geom_line() +
      # use the tidy evaluation pronoun .data to slice the chosen facet_wrap
      # variable from the data frame
      facet_wrap(~ .data[[facet]], ncol = 5) +
      xlab("Date") +
      ylab("Log Cumulative Cases") +
      scale_y_log10(
        breaks = trans_breaks("log10", function(x) 10^x),
        labels = trans_format("log10", math_format(10^.x))
      ) +
      scale_color_manual(
        aesthetics = c("color", "fill"),
        name = NULL, values = my_palette
      )

    dc <- filter(d, variable %in% paste0("daily_", status))
    daily_cases_plot <- ggplot(
      data = dc,
      aes(
        x = date, y = cases, color = .data[[fill]],
        fill = .data[[fill]]
      )
    ) +
      geom_point(size = 0.5) +
      geom_line() +
      facet_wrap(~ .data[[facet]], ncol = 5) +
      xlab("Date") +
      ylab("Daily Cases") +
      scale_color_manual(
        aesthetics = c("color", "fill"),
        name = NULL, values = my_palette
      )
  }

  if (plot == TRUE) {
    return(list(
      totals = totals,
      cum_cases_plot = cum_cases_plot,
      daily_cases_plot = daily_cases_plot
    ))
  } else {
    return(list(totals = totals))
  }
}
```

# Challenge 1

```{R}
cv_summary(cv_data)
```

# Challenge 2

```{R}
cv_summary(cv_data, country_list = c("United States", "United Kingdom", "Canada", "France", "Italy", "Japan", "China", "Russia", "Iran"))

cv_summary(cv_data, country_list = c("United States", "United Kingdom", "Canada", "France", "Italy", "Japan", "China", "Russia", "Iran"), facet = "variable")
```

# Challenge 3

```{R}
(d <- cv_data %>% filter(population > 1000000) %>% cv_summary(country_list = "All", plot = FALSE))
```

The tibble defined above, **d**, contains summary data for all **94** countries in the dataset that had populations over 1,000,000.

# Challenge 4

```{R}
(overall <- d$totals %>% filter(variable == "confirmed") %>% arrange(desc(rate)))

(daily <- d$totals %>% filter(variable=="daily_confirmed") %>% arrange(desc(rate)))
```

The 10 countries with the highest overall rate of confirmed cases are Qatar, Spain, Ireland, Belgium, Singapore, United States, Italy, Switzerland, United Kingdom, and Bahrain.

The 10 countries with the highest single day rate of confirmed cases are Ecuador, Qatar, France, Ireland, Kuwait, Singapore, Belgium, Bahrain, Spain, and Belarus.


# Challenge 5

```{R}
qqnorm(overall$rate); qqline(log(overall$rate), col = 'red')
qqnorm(log(overall$density)); qqline(log(overall$density), col = 'red')
qqnorm(log(overall$population)); qqline(log(overall$population), col = 'red')
qqnorm(log(overall$gdp_capita)); qqline(log(overall$gdp_capita), col = 'red')

model <- lm(rate ~ log(density) + log(population) + log(gdp_capita) + income, data = overall)
summary(model)
```

In the model above, the predictor variables with slopes significantly different from 0 are population density, GDP per capita, and Low overall income level. 

# Challenge 6

```{R}
library(MASS)
library(MuMIn)


(s <- stepAIC(model, scope = . ~ ., direction = "both"))
summary(s)

r.squaredGLMM(s)

r.squaredGLMM(model)

daily_model <- lm(rate ~ log(density) + log(population) + log(gdp_capita) + income, data = daily)

(s_daily <- stepAIC(daily_model, scope = . ~ ., direction = "both"))
summary(s_daily)
```

Performing stepwise selection using AIC determined that a somewhat more nested model is the preferred model for predicting overall infection rate. This model contains the predictors log(density), log(gdp_capita), and income. The pseudo R2 value associated with the full model is 0.4610 and the value associated with the "best" model described above is 0.4626.

After using AIC to determine the preferred model for the maximum daily infection rate, it was revealed that the set of predictors that best describes rate in this model are only log(density) and log(gdp_capita). Income level is no longer a predictor determined to be important in this model.

# Challenge 7

```{R}
new_model <- lm(rate ~ log(density) + log(gdp_capita) + max_mr + max_sd, data = daily)
summary(new_model)

(s_new <- stepAIC(new_model, scope = . ~ ., direction = "both"))

r.squaredGLMM(s_new)

r.squaredGLMM(s_daily)

detach(package:MASS)
detach(package:MuMIn)
```

As demonstrated by the stepwise selection using AIC above with a model containing the *max_sd* and *max_mr* variables added to the variables previously determined to be the most important predictors of maximum daily infection rate, adding *max_mr* to the model does result in a lower AIC (1303.57) as compared to the one generated using *log(density)* and *log(gdp_capita)* (1313.6). Additionally, the pseudo-R^2 values are also increased in the model using *max_mr* as an additional predictor variable (0.2253 in the model prior to adding the additional variable, 0.2445 in the model with the additional variable).

# Challenge 8

```{R}
library(lme4)

m1 <- lmer(data = cv_data, rate ~ log(density) + log(gdp_capita) + soc_dist + mov_rest + (1 | country) + (1 | date), REML=FALSE)
m2 <- lmer(data = cv_data, rate ~ log(density) + log(gdp_capita) + soc_dist + (1 | country) + (1 | date), REML=FALSE)
m3 <- lmer(data = cv_data, rate ~ log(density) + log(gdp_capita) + mov_rest + (1 | country) + (1 | date), REML=FALSE)
m4 <- lmer(data = cv_data, rate ~ log(density) + soc_dist + mov_rest + (1 | country) + (1 | date), REML=FALSE)
m5 <- lmer(data = cv_data, rate ~ log(gdp_capita) + soc_dist + mov_rest + (1 | country) + (1 | date), REML=FALSE)
m6 <- lmer(data = cv_data, rate ~ log(density) + log(gdp_capita) + (1 | country) + (1 | date), REML=FALSE)
m7 <- lmer(data = cv_data, rate ~ log(density) + soc_dist + (1 | country) + (1 | date), REML=FALSE)
m8 <- lmer(data = cv_data, rate ~ log(density) + mov_rest + (1 | country) + (1 | date), REML=FALSE)
m9 <- lmer(data = cv_data, rate ~ log(gdp_capita) + soc_dist + (1 | country) + (1 | date), REML=FALSE)
m10 <- lmer(data = cv_data, rate ~ log(gdp_capita) + mov_rest + (1 | country) + (1 | date), REML=FALSE)
m11 <- lmer(data = cv_data, rate ~ soc_dist + mov_rest + (1 | country) + (1 | date), REML=FALSE)
m12 <- lmer(data = cv_data, rate ~ log(density) + (1 | country) + (1 | date), REML=FALSE)
m13 <- lmer(data = cv_data, rate ~ log(gdp_capita) + (1 | country) + (1 | date), REML=FALSE)
m14 <- lmer(data = cv_data, rate ~ soc_dist + (1 | country) + (1 | date), REML=FALSE)
m15 <- lmer(data = cv_data, rate ~ mov_rest + (1 | country) + (1 | date), REML=FALSE)
null <- lmer(data = cv_data, rate ~ (1 | country) + (1 | date), REML=FALSE)

library(AICcmodavg)

(aic_table <- aictab(list(m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,m15,null),
  modnames = c("m1","m2","m3","m4","m5","m6","m7","m8","m9","m10","m11","m12","m13","m14","m15","null")
))

library(MuMIn)

r.squaredGLMM(m1)
```

After performing a set of mixed effects models, it was determined that the best model of the complete set that was run was the "full" model (called **m1** above). This model included 4 fixed effects (log(density), log(gdp_capita), soc_dist, and mov_rest) and 2 random effects (country and date). The pseudo R2 values associated with this model are 0.03 (marginal R2) and 0.126 (conditional R2).
